spring:
  application:
    name: apigateway
  secret: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf

api:
  gateway:
    routes:
        - path: "/users/**"
          roles: [ ROLE_ADMIN, ROLE_USER ]
        - path: "/manage/seats"
          roles: [ ROLE_ADMIN, ROLE_USER ]
        - path: "/manage/venue"
          roles: [ ROLE_ADMIN ]
        - path: "/manage/shows"
          roles: [ ROLE_ADMIN ]
        - path: "/manage/event"
          roles: [ ROLE_ADMIN ]
        - path: "/user/**"
          roles: [ ROLE_ADMIN, ROLE_USER ]

manageuser:
  route:
    uri: http://manageusers:8081
eventmanagement:
  route:
    uri: http://eventmanagement:8082